spring:
  data:
    mongodb:
      username: wanjohilewi7
      password: uFOsUKjVvXRK8Smd
      host: localhost
      port: 27017
      database: wave-api-db
      authentication-database: 	SCRAM
server:
  port: 8088
